name: Deploy Github pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # - name: Setup Node
    #   uses: actions/setup-node@v3.5.1
    #   with:
    #     node-version: '15.x'

    - run: npm install && npm run build

    - name: Build and Deploy
      # uses: peaceiris/actions-gh-pages@v3
      uses: JamesIves/github-pages-deploy-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        
